version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-2"
    AWS_ACCOUNT_ID    : "112298774548"
    ECR_REPO_NAME     : "my-test-php"
    ECR_IMAGE_TAG     : "latest"

phases:
  install:
    commands:
      - echo "Check aws and git version"
      - aws --version
      - git --version

  pre_build:
    commands:
      - echo "Login to AWS ECR and get commit id"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION| docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
        # aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 112298774548.dkr.ecr.us-east-2.amazonaws.com

  build:
    commands:
      - echo Building the Docker image...
      - docker images
      - docker build -t $ECR_REPO_NAME:$ECR_IMAGE_TAG .
        # docker build -t my-test-php .

      - docker tag $ECR_REPO_NAME:$ECR_IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME:$ECR_IMAGE_TAG
        # docker tag mytest:latest 112298774548.dkr.ecr.us-east-2.amazonaws.com/mytest:latest

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME:$ECR_IMAGE_TAG
        # docker push 112298774548.dkr.ecr.us-east-2.amazonaws.com/mytest:latest
